version: "3.8"
services: 
    apache:
        image: httpd:alpine
        container_name: My_Container
        ports:
            - 8080:80
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs/
        networks:
            - default
networks:
    default:
        driver: bridge